// graphQL/vue_graphql/src/components/News.vue
<template>
  <div class="news">
    <h1>{{ msg }}</h1>    


    <ul>

      <li v-for="(item,key) of articleList" v-bind:key="key">
          {{item.title}}---{{item.status}}
      </li>      
    </ul>

    <button @click="getData()">
      点击按钮触发事件请求graphQl接口
    </button>

    {{navList}}

  </div>
</template>

<script>

  import gql from 'graphql-tag';

  var navListGql=gql`{
             navList{
              title           
            }

   }`;

   

  export default {
    name: 'app',
    data(){
      return{

        msg:'我是一个新闻页面',
        navList:[]

      }
    },apollo:{


      // articleList:gql`{
      //        articleList{
      //         title,
      //         status
      //       }

      // }`

        articleList:{
          query:gql`query articleList($page:Int!,$pageSize:Int!){
                articleList(page:$page,pageSize:$pageSize){
                  title,
                  status
                }
          }`,
          variables:{
            page:2,
            pageSize:10
          }
        }

      
    },
    methods:{

      getData(){
        

        this.$apollo.addSmartQuery('navList',{          

            query:navListGql,
            result(response){

              console.log(response);

            },error(err){

              consoel.log(err);

            }

        })


      }
    }
 
  }
</script>

<style scoped>

</style>

// graphQL/graphqlAngular/src/app/components/news/news.component.ts
import { Component, OnInit } from '@angular/core';


import { Apollo } from 'apollo-angular';
import gql from 'graphql-tag';

const getarticleListGql = gql`
  query articleList($page:Int!,$pageSize:Int!){
    articleList(page:$page,pageSize:$pageSize){
      title,
      status
    }
  }
`;


@Component({
  selector: 'app-news',
  templateUrl: './news.component.html',
  styleUrls: ['./news.component.styl']
})
export class NewsComponent implements OnInit {

  public list:any[]=[];

  constructor(public apollo:Apollo) { }

  ngOnInit() {
  }

  getData(){

    //获取新闻数据

    this.apollo
    .watchQuery({
      query: getarticleListGql,
      variables: {
        page: 1,
        pageSize:8
      },
    })
    .valueChanges.subscribe((response:any)=>{

      console.log(response.data.articleList);
        this.list=response.data.articleList;

    });



  }

}



<br>



<button (click)="getData()">

  获取新闻数据
</button>

<br>

<hr>

<br>

<ul>

  <li *ngFor="let item of list">

      {{item.title}}
  </li>
</ul>
